spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/algaworks
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /

auth-api:
  username: admin
  password: admin
