spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleapiexample
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8080
  servlet:
    context-path: /

logging:
  file:
    name: ./target/logging/backend.log
